language: ruby
rvm:
 - 2.5.3

services:
  - postgresql

before_script:
  - psql -c 'create database chess_test;' -U postgres

before_install:
  - gem update --system
  - gem update bundler
  - gem install bundler
  
script:
  - bundle exec rake db:migrate RAILS_ENV=test
  - bundle exec rspec